apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/drhelius/grpc-demo-product
    app.openshift.io/vcs-ref: {{ .Values.product.version }}
  labels:
    app: product
    version: {{ .Values.product.version }}
    app.kubernetes.io/name: product
    app.kubernetes.io/version: {{ .Values.product.version }}
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: {{ .Values.appName }}
    app.openshift.io/runtime: golang
    group: {{ .Values.appName }}
  name: product-{{ .Values.product.version }}
spec:
  replicas: {{ .Values.product.replicas }}
  selector:
    matchLabels:
      app: product
      version: {{ .Values.product.version }}
  template:
    metadata:
      annotations:
          sidecar.istio.io/inject: "true"
      labels:
        app: product
        version: {{ .Values.product.version }}
    spec:
      containers:
      - image: {{ .Values.product.image }}:{{ .Values.product.version }}
        imagePullPolicy: Always
        name: product
        ports:
        - containerPort: 5000
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: {{ .Values.limits.cpu }}
            memory: {{ .Values.limits.memory }}Mi
          requests:
            cpu: {{ .Values.requests.cpu }}
            memory: {{ .Values.requests.memory }}Mi
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30